<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' - You are advised to back up your device before visiting the authorised service center.' => '- คุณควรสำรองข้อมูลอุปกรณ์ของคุณก่อนไปที่ศูนย์บริการที่ได้รับอนุญาต',
    '- In the event if extra repairs are required apart from your screen crack, additional charges will be applied.' => '- ในกรณีที่จำเป็นต้องมีการซ่อมเพิ่มเติมนอกเหนือจากรอยแตกของหน้าจอ จะมีการคิดค่าใช้จ่ายเพิ่มเติม',
    'A 6 digit One-time PIN has been sent to you.' => 'ส่ง PIN แบบใช้ครั้งเดียว 6 หลักถึงคุณแล้ว',
    'Alternate Number' => 'หมายเลขสำรอง',
    'Are you sure you want to submit?' => 'คุณแน่ใจหรือไม่ว่าต้องการส่ง',
    'Claim submit fail!' => 'การส่งการอ้างสิทธิ์ล้มเหลว',
    'Claim submitted!' => 'ส่งการอ้างสิทธิ์แล้ว',
    'Country' => 'ประเทศ',
    'Coverage Period' => 'ระยะเวลาคุ้มครอง',
    'Created At' => 'สร้างเมื่อ',
    'Device' => 'มือถือ',
    'Device info' => 'ข้อมูลอุปกรณ์',
    'Did not receive your OTP?' => 'ไม่ได้รับ OTP ของคุณใช่หรือไม่',
    'Disclaimers' => 'ข้อจำกัดความรับผิดชอบ',
    'Eg. On the 12th of Jan 2020, I dropped my phone onto the pavement while crossing the street at Yishun Park...' => 'ในวันที่ 12 มกราคม 2020 ฉันทิ้งโทรศัพท์ลงบนทางเท้าขณะข้ามถนนที่ Yishun Park ...',
    'Email' => 'อีเมล',
    'Enter the code to continue' => 'ป้อนรหัสเพื่อดำเนินการต่อ',
    'General' => 'ทั่วไป',
    'Home' => 'หน้าแรก',
    'I have backed up my device' => 'ข้าพเจ้าได้สำรองข้อมูลอุปกรณ์ของข้าพเจ้าแล้ว',
    'I have read and agree to the Terms and Conditions' => 'ฉันได้อ่านและยอมรับข้อกำหนดและเงื่อนไขแล้ว',
    'I understand that there will be additional charges if the repairs goes beyond my plan coverage' => 'ข้าพเจ้าเข้าใจว่าจะมีค่าใช้จ่ายเพิ่มเติม หากการซ่อมเกินความครอบคลุมของแผนของข้าพเจ้า',
    'Last Updated At' => 'อัปเดตล่าสุดที่',
    'Logout' => 'ออกจากระบบ',
    'Max 5 images' => 'สูงสุด 5 ภาพ',
    'Message from InstaProtection' => 'ข้อความจาก InstaProtection',
    'Mobile' => 'หมายเลขมือถือ',
    'Mode' => 'โหมด',
    'Model Number' => 'หมายเลขรุ่น',
    'No QR code detected.' => 'ไม่พบคิวอาร์โค้ด',
    'No plan details' => 'ไม่มีรายละเอียดแผน',
    'One-Time Pin' => 'PIN แบบใช้ครั้งเดียว',
    'Only can proceed to claim when plan is active!' => 'สามารถดำเนินการอ้างสิทธิ์ได้เมื่อแผนใช้งานอยู่เท่านั้น',
    'Only can proceed when claim requires clarification!' => 'สามารถดำเนินการต่อเมื่อการอ้างสิทธิ์ต้องการคำชี้แจงเท่านั้น',
    'Other charges:' => 'ค่าบริการอื่นๆ:',
    'Plan Details' => 'รายละเอียดแผน',
    'Plan Name' => 'ชื่อแผน',
    'Plan Status' => 'สถานะแผน',
    'Plans' => 'แผน',
    'Please check your' => 'โปรดตรวจสอบไฟล์',
    'Please contact InstaProtection.' => 'กรุณาติดต่อ InstaProtection',
    'Please describe the events of incident saying the date and time of the incident, where and how it happened. You are also recommended to attach photos of the damaged phone and provide an alternative phone number for contact.' => 'โปรดอธิบายเหตุการณ์โดยระบุวันที่และเวลาของเหตุการณ์และเหตุการณ์ที่เกิดขึ้น นอกจากนี้คุณควรแนบรูปถ่ายของโทรศัพท์ที่เสียหายและระบุหมายเลขโทรศัพท์อื่นเพื่อใช้ในการติดต่อ',
    'Please select from the dropdown list for our partner repair centers to visit for your repairs.' => 'โปรดเลือกจากรายการแบบเลื่อนลงสำหรับศูนย์ซ่อมพันธมิตรของเราเพื่อเยี่ยมชมการซ่อมแซมของคุณ',
    'Policy Details' => 'รายละเอียดนโยบาย',
    'Purchase From' => 'ซื้อจาก',
    'Resend OTP' => 'ส่ง OTP อีกครั้ง',
    'SMS' => 'ข้อความ',
    'Select repair centre' => 'เลือกศูนย์ซ่อมบำรุง',
    'Sign In' => 'เข้าสู่ระบบ',
    'Sign me in' => 'ลงชื่อเข้าใช้',
    'Submit' => 'ส่ง',
    'Submit Claim' => 'ส่งการเคลม',
    'Submit Clarification' => 'ส่งคำชี้แจง',
    'Submit a Claim' => 'ส่งการเคลม',
    'The requested page does not exist.' => 'ไม่มีหน้าที่ร้องขออยู่',
    'Upload Photo' => 'อัปโหลดภาพถ่าย',
    'View Terms and Conditions' => 'ดูข้อกำหนดและเงื่อนไขแล้ว',
    'Your description should not more than 500 characters.' => 'คำอธิบายของคุณไม่ควรเกิน 500 อักขระ',
    'inbox.' => 'กล่องจดหมาย',
    'Captcha' => '',
    'Member since {0, date, short}' => '',
    'Submit clarification' => '',
    'There is currently no service centres found for your phone model.' => '',
    '{username}' => '',
];
