<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' - You are advised to back up your device before visiting the authorised service center.' => '- Anda dinasihati untuk membuat sandaran bagi peranti anda sebelum mengunjungi pusat servis yang dibenarkan.',
    '- In the event if extra repairs are required apart from your screen crack, additional charges will be applied.' => '- Jika pembaikan tambahan diperlukan selain keretakan skrin anda, caj tambahan akan dikenakan.',
    'A 6 digit One-time PIN has been sent to you.' => 'PIN Guna Sekali 6 digit telah dihantar kepada anda.',
    'Alternate Number' => 'Nombor Ganti',
    'Are you sure you want to submit?' => 'Adakah anda pasti ingin serahkan?',
    'Claim submit fail!' => 'Penyerahan tuntutan gagal!',
    'Claim submitted!' => 'Tuntutan dikemukakan!',
    'Coverage Period' => 'Tempoh Liputan',
    'Created At' => 'Dibuat pada',
    'Device' => 'Peranti',
    'Device info' => 'Maklumat peranti',
    'Did not receive your OTP?' => 'Tidak menerima OTP anda?',
    'Disclaimers' => 'Penafian',
    'Eg. On the 12th of Jan 2020, I dropped my phone onto the pavement while crossing the street at Yishun Park...' => 'Cth. Pada 12 Januari 2020, saya menjatuhkan telefon saya ke trotoar semasa melintasi jalan di Taman Yishun ...',
    'Email' => 'E-mel',
    'Enter the code to continue' => 'Masukkan kod untuk sambung',
    'General' => 'Umum',
    'Home' => 'Laman Utama',
    'I have backed up my device' => 'Saya telah membuat sandaran bagi peranti saya.',
    'I have read and agree to the Terms and Conditions' => 'Saya telah membaca dan bersetuju dengan Terma dan Syarat',
    'I understand that there will be additional charges if the repairs goes beyond my plan coverage' => 'Saya memahami bahawa terdapat caj tambahan jika pembaikan melebihi liputan pelan saya.',
    'Last Updated At' => 'Terakhir Dikemas Kini Pada',
    'Logout' => 'Log Keluar',
    'Max 5 images' => 'Maksimum 5 gambar',
    'Message from InstaProtection' => 'Mesej dari InstaProtection',
    'Mobile' => 'No telefon bimbit',
    'Model Number' => 'Nombor model',
    'No QR code detected.' => 'Tiada kod QR dikesan.',
    'One-Time Pin' => 'Pin Guna Sekali',
    'Only can proceed to claim when plan is active!' => 'Hanya boleh membuat tuntutan semasa pelan aktif',
    'Other charges:' => 'Caj lain:',
    'Plan Name' => 'Name Pelan',
    'Plan Status' => 'Status Pelan',
    'Plans' => 'Pelan',
    'Please describe the events of incident saying the date and time of the incident, where and how it happened. You are also recommended to attach photos of the damaged phone and provide an alternative phone number for contact.' => 'Terangkan peristiwa kejadian yang menyatakan tarikh dan masa kejadian, di mana dan bagaimana kejadiannya. Anda juga disarankan untuk melampirkan foto telefon yang rosak dan memberikan nombor telefon alternatif untuk dihubungi.',
    'Please select from the dropdown list for our partner repair centers to visit for your repairs.' => 'Sila pilih dari senarai dropdown untuk pusat pembaikan rakan kongsi kami untuk dikunjungi untuk pembaikan anda.',
    'Policy Details' => 'Butiran Polisi',
    'Purchase From' => 'Pembelian Daripada',
    'Resend OTP' => 'Hantar Semula OTP',
    'Select repair centre' => 'Pilih pusat pembaikan',
    'Sign In' => 'Daftar Masuk',
    'Sign me in' => 'Daftar masuk saya',
    'Submit' => 'Serah',
    'Submit Claim' => 'Serah Tuntutan',
    'Submit Clarification' => 'Serah Penjelasan',
    'Submit a Claim' => 'Serah Tuntutan',
    'The requested page does not exist.' => 'Halaman yang diminta tidak wujud.',
    'Upload Photo' => 'Muat Naik Gambar',
    'View Terms and Conditions' => 'Lihat Terma dan Syarat',
    'Your description should not more than 500 characters.' => 'Huraian anda tidak boleh melebihi 500 aksara.',
    'inbox.' => 'Peti masuk',
    'Captcha' => '',
    'Country' => '',
    'Member since {0, date, short}' => '',
    'Mode' => '',
    'No plan details' => '',
    'Only can proceed when claim requires clarification!' => '',
    'Plan Details' => '',
    'Please check your' => '',
    'Please contact InstaProtection.' => '',
    'SMS' => '',
    'Submit clarification' => '',
    'There is currently no service centres found for your phone model.' => '',
    '{username}' => '',
];
