<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' - You are advised to back up your device before visiting the authorised service center.' => '- Anda disarankan untuk mencadangkan perangkat Anda sebelum mengunjungi pusat layanan resmi.',
    '- In the event if extra repairs are required apart from your screen crack, additional charges will be applied.' => 'Jika perbaikan tambahan diperlukan selain layar yang retak  biaya tambahan akan dikenakan.<br>',
    'A 6 digit One-time PIN has been sent to you.' => 'PIN Satu Kali 6 digit telah dikirimkan kepada Anda.',
    'Alternate Number' => 'Nomor Alternatif',
    'Are you sure you want to submit?' => 'Apakah Anda yakin ingin mengirimkan?',
    'Claim submit fail!' => 'Kirim klaim gagal!',
    'Claim submitted!' => 'Klaim diajukan!',
    'Country' => 'Negara',
    'Coverage Period' => 'Tempoh Liputan',
    'Created At' => 'Dibuat pada',
    'Device' => 'perangkat',
    'Device info' => 'Info perangkat',
    'Did not receive your OTP?' => 'Tidak menerima OTP Anda?',
    'Disclaimers' => 'Penafian',
    'Eg. On the 12th of Jan 2020, I dropped my phone onto the pavement while crossing the street at Yishun Park...' => 'Misalnya. Pada 12 Jan 2020, saya menjatuhkan ponsel saya ke trotoar saat menyeberang jalan di Taman Yishun ...',
    'Email' => 'Email',
    'Enter the code to continue' => 'Masukkan kode untuk melanjutkan',
    'General' => 'Umum',
    'Home' => 'Beranda',
    'I have backed up my device' => 'Saya telah mencadangkan perangkat saya.',
    'I have read and agree to the Terms and Conditions' => 'Saya telah membaca dan menyetujui Syarat dan Ketentuan',
    'I understand that there will be additional charges if the repairs goes beyond my plan coverage' => 'Saya memahami bahwa akan ada biaya tambahan jika perbaikan melampaui pertanggungan program saya.',
    'Last Updated At' => 'Terakhir Diperbarui Pada',
    'Logout' => 'Keluar',
    'Max 5 images' => 'Maks 5 gambar',
    'Message from InstaProtection' => 'Pesan dari InstaProtection',
    'Mobile' => 'No Hp',
    'Model Number' => 'Nomor model',
    'No QR code detected.' => 'Tidak ada kode QR yang terdeteksi',
    'One-Time Pin' => 'Pin Satu Kali',
    'Other charges:' => 'Biaya lainnya:',
    'Plan Name' => 'Name Program',
    'Plan Status' => 'Status Program',
    'Plans' => 'Program',
    'Please select from the dropdown list for our partner repair centers to visit for your repairs.' => 'Pilih dari daftar tarik-turun pusat perbaikan mitra kami yang akan dikunjungi untuk perbaikan Anda.',
    'Policy Details' => 'Rincian Polis',
    'Purchase From' => 'Pembelian Daripada',
    'Resend OTP' => 'Kirim ulang OTP',
    'Select repair centre' => 'Pilih pusat perbaikan',
    'Sign In' => 'Masuk',
    'Sign me in' => 'Masukkan saya',
    'Submit' => 'Kirim',
    'Submit Claim' => 'Kirim Klaim',
    'Submit Clarification' => 'Kirim Klarifikasi',
    'Submit a Claim' => 'Kirim Klaim',
    'The requested page does not exist.' => 'Halaman yang diminta tidak ada.',
    'Upload Photo' => 'Unggah Foto',
    'View Terms and Conditions' => 'Lihat Syarat dan Ketentuan',
    'Your description should not more than 500 characters.' => 'Deskripsi Anda tidak boleh lebih dari 500 karakter.',
    'inbox.' => 'Kotak Masuk',
    'Captcha' => '',
    'Member since {0, date, short}' => '',
    'Mode' => '',
    'No plan details' => '',
    'Only can proceed to claim when plan is active!' => '',
    'Only can proceed when claim requires clarification!' => '',
    'Plan Details' => '',
    'Please check your' => '',
    'Please contact InstaProtection.' => '',
    'Please describe the events of incident saying the date and time of the incident, where and how it happened. You are also recommended to attach photos of the damaged phone and provide an alternative phone number for contact.' => '',
    'SMS' => '',
    'Submit clarification' => '',
    'There is currently no service centres found for your phone model.' => '',
    '{username}' => '',
];
