<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => '',
    'Address' => '',
    'Address Delivery' => '',
    'Allowance' => '',
    'Allowance Updated At' => '',
    'Case ID' => '',
    'Claim Number' => '',
    'Claim Type ID' => '',
    'Company Name' => '',
    'Courier Payer ID' => '',
    'Created At' => '',
    'Created By' => '',
    'Dealer Company ID' => '',
    'Device Color ID' => '',
    'Device ID' => '',
    'Device Issue' => '',
    'Duplicate imei number.' => '',
    'Email' => '',
    'Endpoint' => '',
    'Error deleting post.' => '',
    'Error removing vote.' => '',
    'Error reporting post.' => '',
    'Error voting.' => '',
    'First Name' => '',
    'Has Courier' => '',
    'ID' => '',
    'Imei' => '',
    'Insurance Category ID' => '',
    'Invalid id_hash.' => '',
    'Last Name' => '',
    'Mobile Number' => '',
    'No user.' => '',
    'Plan Pool ID' => '',
    'Policy Number' => '',
    'Policy Plan ID' => '',
    'Region ID' => '',
    'Remarks' => '',
    'Repair Centre ID' => '',
    'Serial Number' => '',
    'Token' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'Verify token cannot be blank.' => '',
    'Wrong verify token.' => '',
];
