<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' - You are advised to back up your device before visiting the authorised service center.' => '',
    '- In the event if extra repairs are required apart from your screen crack, additional charges will be applied.' => '',
    'A 6 digit One-time PIN has been sent to you.' => '',
    'Alternate Number' => '',
    'Are you sure you want to submit?' => '',
    'Captcha' => '',
    'Claim submit fail!' => '',
    'Claim submitted!' => '',
    'Country' => '',
    'Coverage Period' => '',
    'Created At' => '',
    'Device' => '',
    'Device info' => '',
    'Did not receive your OTP?' => '',
    'Disclaimers' => '',
    'Eg. On the 12th of Jan 2020, I dropped my phone onto the pavement while crossing the street at Yishun Park...' => '',
    'Email' => '',
    'Enter the code to continue' => '',
    'General' => '',
    'Home' => '',
    'I have backed up my device' => '',
    'I have read and agree to the Terms and Conditions' => '',
    'I understand that there will be additional charges if the repairs goes beyond my plan coverage' => '',
    'Last Updated At' => '',
    'Logout' => '',
    'Max 5 images' => '',
    'Member since {0, date, short}' => '',
    'Message from InstaProtection' => '',
    'Mobile' => '',
    'Mode' => '',
    'Model Number' => '',
    'No QR code detected.' => '',
    'No plan details' => '',
    'One-Time Pin' => '',
    'Only can proceed to claim when plan is active!' => '',
    'Only can proceed when claim requires clarification!' => '',
    'Other charges:' => '',
    'Plan Details' => '',
    'Plan Name' => '',
    'Plan Status' => '',
    'Plans' => '',
    'Please check your' => '',
    'Please contact InstaProtection.' => '',
    'Please describe the events of incident saying the date and time of the incident, where and how it happened. You are also recommended to attach photos of the damaged phone and provide an alternative phone number for contact.' => '',
    'Please select from the dropdown list for our partner repair centers to visit for your repairs.' => '',
    'Policy Details' => '',
    'Purchase From' => '',
    'Resend OTP' => '',
    'SMS' => '',
    'Select repair centre' => '',
    'Sign In' => '',
    'Sign me in' => '',
    'Submit' => '',
    'Submit Claim' => '',
    'Submit Clarification' => '',
    'Submit a Claim' => '',
    'Submit clarification' => '',
    'The requested page does not exist.' => '',
    'There is currently no service centres found for your phone model.' => '',
    'Upload Photo' => '',
    'View Terms and Conditions' => '',
    'Your description should not more than 500 characters.' => '',
    'inbox.' => '',
    '{username}' => '',
];
