<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hi Sir/ Madam,' => "Chào ông / bà,",
    'Please kindly log in to the application/website to check.' => "Vui lòng đăng nhập vào ứng dụng / trang web để kiểm tra.",
    'Contact our Customer Service should you need any assistance.' => "Liên hệ với Dịch vụ khách hàng của chúng tôi nếu bạn cần bất kỳ hỗ trợ nào.",
];
